# -*- coding: utf-8 -*-
"""Regresi Logistik menentukan calon pembeli mobil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jg2Sr9SPpDMbz3nIxgyC5e3QdI7okc2m
"""

#membaca file
import pandas as pd
df = pd.read_csv("/content/calonpembeli_ch5.csv")
df.head()

#melihat deskripsi dari file
df.describe()

#pada kolom usia terdapat umur 164 sehingga kita harus mengeluarkan usia yang tidak masuk akal yaitu umur > 100 tahun
df = df[df["Usia"] <=100]

#melihat kembali nilai deskripsi data
df.describe()

#melakukan pengecekan data apakah terdapat nilai null atau tidak
df.isnull().sum()

#menghitung 2 jumlah kelompok dimana 1 = membeli mobil dan 0 = tidak membeli mobil
df["Beli_Mobil"].value_counts()

#menentukan fitur dan target dan membagi dataset
import sklearn.model_selection as ms
X = df[['Usia','Status','Kelamin','Memiliki_Mobil','Penghasilan']]
y = df['Beli_Mobil']
X_train,X_test,y_train,y_test = ms.train_test_split(X,y,test_size = 0.2, random_state = 0)

#Menentukan model
import sklearn.linear_model as lm
model = lm.LogisticRegression(solver='lbfgs')
model.fit(X_train,y_train)

#menampilkan model koefisien
print(model.coef_)

#memprediksi model
y_pred = model.predict(X_test)
print(y_pred)

#melihat hasil dari X_test
X_test.head()

#melihat hasil dari y_test
y_test.head(3)

#melihat nilai matrix confusional
import sklearn.metrics as met
confusionalmatrix = met.confusion_matrix(y_test,y_pred)
print(confusionalmatrix)

#menghitung skor model
skor = model.score(X_test,y_test)
print(skor)

#menghitung Presisi model
presisi = met.precision_score (y_test, y_pred)
print(presisi)

#menghitung AUC(Area Under Curve)
auc = met.roc_auc_score(y_test, y_pred)
print(auc)

#menamppilkan visualisasi ROC
import matplotlib.pyplot as plt
y_pred_proba = model.predict_proba(X_test)[::,1]
fp, tp, _ = met.roc_curve(y_test, y_pred_proba)
auc = met.roc_auc_score(y_test,y_pred_proba)
plt.plot(fp,tp,label="data 1,auc="+str(auc))
plt.show()

